version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "GatorPolls"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-oth3brnc6i5j"
s3_prefix = "GatorPolls"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
